# Generated by Django 3.2.5 on 2021-07-09 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survivor',
            old_name='sexo',
            new_name='sex',
        ),
    ]
