# Generated by Django 3.2.5 on 2021-07-09 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_sexo_survivor_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water', models.IntegerField(blank=True, null=True)),
                ('food', models.IntegerField(blank=True, null=True)),
                ('medicine', models.IntegerField(blank=True, null=True)),
                ('ammunition', models.IntegerField(blank=True, null=True)),
                ('survivor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.survivor')),
            ],
        ),
    ]
