# Generated by Django 3.2.5 on 2021-07-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='survivor',
            name='infected_report',
            field=models.IntegerField(default=0),
        ),
    ]
